### ISSUE TITLE
Definitely needs Symfony 6 support...

### ISSUE THREAD

**Issue by hopeseekr** [scrawler-labs/router#12]
I had major conflicts with my existing project and had to temporarily abandon adoption of this project.

A sizable portion of the PHP ecosystem has already started requiring a minimum of Symfony 6, which was released in December 2021, including my project. This inhibits adoption.

**Comment by ipranjal** [comment]
Symphony is not much of a greator dependency for this project and I’ll upgrade to symphony 6 right away

**Comment by ipranjal** [comment]
@hopeseekr all deps are now updated to use symphony 6 , its also compatible with symphony 5 , let me know if you find anything else as issue

**Comment by ipranjal** [comment]
v3.1.0 is released with all dep fixes https://github.com/scrawler-labs/router/releases/tag/v3.1.0
